### ISSUE TITLE
Having trouble syncing with AnkiDroid

### ISSUE THREAD

**Issue by colonelsmoothie** [dsnopek/anki-sync-server#52]
Hello,

Thanks for working on this!

I've been trying to use anki-sync-server to see if I could sync to a collection on a personal server from my phone:

https://github.com/dsnopek/anki-sync-server

After much wrangling, I have been able to get the server running, so I can sync my Anki Desktop application to it. However, I've been having trouble getting my phone to sync with it using the following entries in the AnkiDroid Custom Sync server:

Sync url https://192.168.1.149:27701/

Media sync url https://192.168.1.149:27701/msync/

This IP address match what I have on my production.ini file and the mysyncserver.py plugin file. But when I try to sync with AnkiDroid on my home wifi, I am immediately getting a connection timeout error message, so I believe I may have missed something in configuring the server. However, the message takes less than a second to appear, so I don't think it's a matter of the connection taking too long, it seems to be denied altogether.

Can you please help me with this?

Thanks!

**Comment by ninja33** [comment]
maybe you need check local firewall configuration.

**Comment by colonelsmoothie** [comment]
Thanks for the quick reply. I tried each of the following:

sudo ufw allow 27701

sudo ufw allow ssh

sudo ufw disable

AnkiDroid is still giving the same error for each one. 

sudo ufw status
Status: active

To                         Action      From
--                         ------      ----
27701                      ALLOW       Anywhere                  
22                         ALLOW       Anywhere                  
27701 (v6)                 ALLOW       Anywhere (v6)             
22 (v6)                    ALLOW       Anywhere (v6)  

Is there anything else I can try?

**Comment by ninja33** [comment]
Sorry, my mistake to describe it as firewall, actually, I mean network interface for inbound connection.
127.0.0.1 for desktop Anki is just loop-back interface, right?
So you need enable inbound connection for local network.  192.168.1.0 mask:0.0.0.255
I don't think it's port issue as you mentioned above.

I am not familiar with Ubuntu command to config it.
maybe, you can check #49

**Comment by colonelsmoothie** [comment]
Got it working! woohoo!

I tried connecting to the server with a laptop instead, which worked. Looked carefully and noticed that the server had 'http' instead of 'https'...changed AnkiDroid to match and got it to work!

silly me...

Thanks!
