### ISSUE TITLE
Syncing inconsistencies

### ISSUE THREAD

**Issue by DirtYiCE** [dsnopek/anki-sync-server#57]
I switched from AnkiWeb to this sync server a few days ago, and I've encountered this problem multiple times since then. Tried `Check Database`, and full sync multiple times, but it didn't solve my problem.

I couldn't exactly pinpoint what causes this problem, but is seems like doing a bunch of reviews or editing a few cards can trigger this error. After doing some reviews on AnkiDroid and then sync, when I try to sync with desktop anki, I sometimes get "Your collection is in an inconsistent state." error, and forces a full sync. The same can happen if I edit my cards on desktop, and try to sync back to AnkiDroid.

I tried what happens if I leave out AnkiDroid and try to sync between two desktop an ankis. I've rescheduled some cards on computer A, synced A, synced B, looks ok, except the changes are not visible on B. If I force a full sync, changes appear on computer B too.

I use the version from pip in a virtualenv (I had to work-around #40 by moving the `anki-bundled` folder into `lib/python2.7/site-packages`...). `ankiserverctl.py debug` doesn't show any obvious errors or problems.

**Comment by aikalant** [comment]
I think that it can be fixed with the patch files from https://github.com/dsnopek/anki-sync-server/issues/47

**Comment by DirtYiCE** [comment]
It seems like it fixed it, even though I received different error message. Thanks!

**Comment by aikalant** [comment]
I know you closed the thread, and I don't know what error you are still receiving, but I was running into some more server issues until I applied the fix from here

https://github.com/dsnopek/anki-sync-server/issues/44

**Comment by DirtYiCE** [comment]
I received "Your collection is in an inconsistent state." messages until I applied the fix from #44. Now they disappeared (although syncing on AnkiDroid takes a long time if I modify cards from desktop Anki, looks like somewhy it implicitly runs check database/media on sync.. so it's not 100%)
