### ISSUE TITLE
Error sync after update local app

### ISSUE THREAD

**Issue by LxPvlv** [dsnopek/anki-sync-server#59]
- OS:  Archlinux
- About Anki:  Version 2.1.0a10
- Qt 5.8.0 PyQt 5.7.1

After update descktop app fulfilled daily tasks. Pressed 'Sinchronize  with AnkiWeb' and got following error.

```
An error occurred. It may have been caused by a harmless bug, 
or your deck may have a problem. 
To confirm it's not a problem with your deck, please run Tools > Check Database. 
If that doesn't fix the problem, please copy the following
into a bug report:
Caught exception:
  File "/usr/share/anki/aqt/sync.py", line 346, in run
    self.col.close(save=False)
  File "/usr/share/anki/anki/collection.py", line 156, in close
    self.db.execute("pragma journal_mode = delete")
  File "/usr/share/anki/anki/db.py", line 31, in execute
    res = self._db.execute(sql, a)
<class 'sqlite3.OperationalError'>: cannot change out of wal mode from within a transaction
```
Local base and AnkiWeb were sinchronized. But this message appear every time.
Check Dtabase - OK.

**Comment by agrueneberg** [comment]
This was fixed in dae/anki@4430785122d57eb1f3564b9bd06f4636bda77e63. It wasn't related to anki-sync-server. I'm not sure if the maintainer of the Arch Linux anki package intentionally updated to an alpha version, but it seems a little early. Might cause some headaches for @dae.

**Comment by Akendo** [comment]
Welcome to ArchLinux ;-)

**Comment by agrueneberg** [comment]
I did some research and it looks like `qtwebkit` was phased out because it's unmaintained and riddled with security issues: https://www.archlinux.org/todo/phasing-out-qtwebkit/ The current stable version of Anki has a dependency on it, but Anki 2.1 doesn't (it uses `qt5-webengine` instead). That explains the update to an alpha version.

**Comment by hnykda** [comment]
I confirm that applying the fix from [here](https://github.com/dae/anki/commit/4430785122d57eb1f3564b9bd06f4636bda77e63) manually in `/usr/share/anki/anki/collection.py` works. It is a quick fix for those who wanna use the version from the official repositories.

**Comment by agrueneberg** [comment]
The anki package has been removed from the official repositories. It is recommended to use the binary version from https://apps.ankiweb.net/ instead.

**Comment by Akendo** [comment]
seems like bad idea....
